# Generated by Django 4.2.2 on 2023-07-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, help_text='Longhand state name.', max_length=28),
        ),
    ]
