# Generated by Django 4.2.2 on 2023-07-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tract',
            name='fips',
            field=models.CharField(help_text='Eleven-digit tract FIPS.', max_length=11, unique=True),
        ),
    ]
