# Generated by Django 4.2.2 on 2023-07-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_tract_fips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coalclosures',
            old_name='tract_geoid',
            new_name='tract_fips',
        ),
    ]
