# Generated by Django 4.2.2 on 2023-07-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_rename_tract_geoid_coalclosures_tract_fips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coalclosures',
            name='added',
            field=models.DateField(blank=True, help_text='\n            Date added (n.b., reflects data as acquired,\n            not this database instance).\n            ', null=True),
        ),
        migrations.AlterField(
            model_name='coalclosures',
            name='last_update',
            field=models.DateField(blank=True, help_text='\n            Date last updated (n.b., reflects data as acquired,\n            not this database instance).\n            ', null=True),
        ),
        migrations.AlterField(
            model_name='coalclosures',
            name='version',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Dataset version.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ffe',
            name='added',
            field=models.DateField(blank=True, help_text='\n            Date added (n.b., reflects data as acquired,\n            not this database instance).\n            ', null=True),
        ),
        migrations.AlterField(
            model_name='ffe',
            name='last_update',
            field=models.DateField(blank=True, help_text='\n            Date last updated (n.b., reflects data as acquired,\n            not this database instance).\n            ', null=True),
        ),
        migrations.AlterField(
            model_name='ffe',
            name='version',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Dataset version.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='added',
            field=models.DateField(blank=True, help_text='\n            Date added (n.b., reflects data as acquired,\n            not this database instance).\n            ', null=True),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='last_update',
            field=models.DateField(blank=True, help_text='\n            Date last updated (n.b., reflects data as acquired,\n            not this database instance).\n            ', null=True),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='version',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Dataset version.', max_digits=5, null=True),
        ),
    ]
